version: 0.2

phase:
        pre_build:
                commands:
                        - echo 'Installing requirements..'
                        - pip install -r requirements.txt
                        - echo 'Running tests on $CODEBUILD_SOURCE_VERSION..'
        build:
                commands:
                        - echo 'Running tests..'
                        - nosetests -x
                        - echo 'Tests ran with exit code $?'
                        - echo '#!/bin/bash' > /usr/local/bin/ok; echo 'if [[ "$?" == "1" ]]; then exit 1; else exit 0; fi' >> /usr/local/bin/ok; chmod +x /usr/local/bin/ok
        artifacts:
                files:
                        - '**/*'
