version: 0.2

phase:
        pre_build:
                commands:
                        - pip install -r requirements.txt
        build:
                commands:
                        - nosetests
                        - flake8 --config=tox.ini
        artifacts:
                files:
                        - '**/*'
